const projects = [
  id: '1',
  images: './img/img-placeholder1.png',
  image1: 'img/image-hover.png',
  title: 'Professional Art Printing',
  paragraph: 'A daily selection of privately personalized reads; no accounts or sign-ups required. has been the industrys standard',
  languages: ['html', 'bootstrap', 'Ruby'],
  seeBtn: 'See Project',
  imageDesktop: 'img/SnapshootPortfolioDesktop.png',
  imageMobile: 'img/SnapshootPortfolioMobile.png',
  desktopTitle: 'Keeping track of hundreds of components website 1',
  desktopText: ['Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry´s standard dummy text ever since the 1500s,',
   'when an unknown printer took a galley of type and scrambled it in 1960s.<br>',
   'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry´s standard dummy text ever since the 1500s,',
   'when an unknown printer took a galley of type and scrambled it in 1960s with the releax map lapora verita.'],
  mobileTitle: 'Multi-Post Stories',
  mobileText: ['Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry´s standard dummy text ever since the 1500s,',
   'when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into',
   'electronic typesetting, remaining essent'],
  tools: ['html', 'bootstrap', 'Ruby on Rails'],
  closeImage: 'img/x-mobile.png',
  liveBtn: 'See live',
  sourceBtn: 'See source',
  live: 'https://eamador1.github.io/portfolio/',
  source: 'https://github.com/eamador1/portfolio/blob/main/index.html',
 },
 {
  id: '2',
  images: './img/image-background2.png',
  image1: 'img/image-hover.png',
  title: 'Data Dashboard Healthcare',
  paragraph: 'A daily selection of privately personalized reads; no accounts or sign-ups required. has been the industrys standard',
  languages: ['html', 'bootstrap', 'Ruby'],
  seeBtn: 'See Project',
  imageDesktop: 'img/SnapshootPortfolioDesktop.png',
  imageMobile: 'img/SnapshootPortfolioMobile.png',
  desktopTitle: 'Keeping track of hundreds of components website 1',
  desktopText: ['Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry´s standard dummy text ever since the 1500s,',
   'when an unknown printer took a galley of type and scrambled it in 1960s.<br>',
   'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry´s standard dummy text ever since the 1500s,',
   'when an unknown printer took a galley of type and scrambled it in 1960s with the releax map lapora verita.'],
  mobileTitle: 'Multi-Post Stories',
  mobileText: ['Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry´s standard dummy text ever since the 1500s,',
   'when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into',
   'electronic typesetting, remaining essent'],
  tools: ['html', 'bootstrap', 'Ruby on Rails'],
  closeImage: 'img/x-mobile.png',
  liveBtn: 'See live',
  sourceBtn: 'See source',
  live: 'https://eamador1.github.io/portfolio/',
  source: 'https://github.com/eamador1/portfolio/blob/main/index.html',
 },
 {
  id: '3',
  images: './img/image-background3.png',
  image1: 'img/image-hover.png',
  title: 'Website Portfolio',
  paragraph: 'A daily selection of privately personalized reads; no accounts or sign-ups required. has been the industrys standard',
  languages: ['html', 'boostrap', 'Ruby'],
  seeBtn: 'See Project',
  imageDesktop: 'img/SnapshootPortfolioDesktop.png',
  imageMobile: 'img/SnapshootPortfolioMobile.png',
  desktopTitle: 'Keeping track of hundreds of components website 1',
  desktopText: ['Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry´s standard dummy text ever since the 1500s,',
   'when an unknown printer took a galley of type and scrambled it in 1960s.<br>',
   'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry´s standard dummy text ever since the 1500s,',
   'when an unknown printer took a galley of type and scrambled it in 1960s with the releax map lapora verita.'],
  mobileTitle: 'Multi-Post Stories',
  mobileText: ['Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry´s standard dummy text ever since the 1500s,',
   'when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into',
   'electronic typesetting, remaining essent'],
  tools: ['html', 'bootstrap', 'Ruby on Rails'],
  closeImage: 'img/x-mobile.png',
  liveBtn: 'See live',
  sourceBtn: 'See source',
  live: 'https://eamador1.github.io/portfolio/',
  source: 'https://github.com/eamador1/portfolio/blob/main/index.html',
 },
 {
  id: '4',
  images: './img/img-placeholder1.png',
  image1: 'img/image-hover.png',
  title: 'Professional Art Printing',
  paragraph: 'A daily selection of privately personalized reads; no accounts or sign-ups required. has been the industrys standard',
  languages: ['html', 'bootstrap', 'Ruby'],
  seeBtn: 'See Project',
  imageDesktop: 'img/SnapshootPortfolioDesktop.png',
  imageMobile: 'img/SnapshootPortfolioMobile.png',
  desktopTitle: 'Keeping track of hundreds of components website 1',
  desktopText: ['Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry´s standard dummy text ever since the 1500s,',
   'when an unknown printer took a galley of type and scrambled it in 1960s.<br>',
   'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry´s standard dummy text ever since the 1500s,',
   'when an unknown printer took a galley of type and scrambled it in 1960s with the releax map lapora verita.'],
  mobileTitle: 'Multi-Post Stories',
  mobileText: ['Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry´s standard dummy text ever since the 1500s,',
   'when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into',
   'electronic typesetting, remaining essent'],
  tools: ['html', 'bootstrap', 'Ruby on Rails'],
  closeImage: 'img/x-mobile.png',
  liveBtn: 'See live',
  sourceBtn: 'See source',
  live: 'https://eamador1.github.io/portfolio/',
  source: 'https://github.com/eamador1/portfolio/blob/main/index.html',
 },
 {
  id: '5',
  images: './img/image-background2.png',
  image1: 'img/image-hover.png',
  title: 'Data Dashboard Healthcare',
  paragraph: 'A daily selection of privately personalized reads; no accounts or sign-ups required. has been the industrys standard',
  languages: ['html', 'bootstrap', 'Ruby'],
  seeBtn: 'See Project',
  imageDesktop: 'img/SnapshootPortfolioDesktop.png',
  imageMobile: 'img/SnapshootPortfolioMobile.png',
  desktopTitle: 'Keeping track of hundreds of components website 1',
  desktopText: ['Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry´s standard dummy text ever since the 1500s,',
   'when an unknown printer took a galley of type and scrambled it in 1960s.<br>',
   'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry´s standard dummy text ever since the 1500s,',
   'when an unknown printer took a galley of type and scrambled it in 1960s with the releax map lapora verita.'],
  mobileTitle: 'Multi-Post Stories',
  mobileText: ['Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry´s standard dummy text ever since the 1500s,',
   'when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into',
   'electronic typesetting, remaining essent'],
  tools: ['html', 'bootstrap', 'Ruby on Rails'],
  closeImage: 'img/x-mobile.png',
  liveBtn: 'See live',
  sourceBtn: 'See source',
  live: 'https://eamador1.github.io/portfolio/',
  source: 'https://github.com/eamador1/portfolio/blob/main/index.html',
 },
 {
  id: '6',
  images: './img/image-background3.png',
  image1: 'img/image-hover.png',
  title: 'Website Portfolio',
  paragraph: 'A daily selection of privately personalized reads; no accounts or sign-ups required. has been the industrys standard',
  languages: ['html', 'bootstrap', 'Ruby'],
  seeBtn: 'See Project',
  imageDesktop: 'img/SnapshootPortfolioDesktop.png',
  imageMobile: 'img/SnapshootPortfolioMobile.png',
  desktopTitle: 'Keeping track of hundreds of components website 1',
  desktopText: ['Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry´s standard dummy text ever since the 1500s,',
   'when an unknown printer took a galley of type and scrambled it in 1960s.<br>',
   'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry´s standard dummy text ever since the 1500s,',
   'when an unknown printer took a galley of type and scrambled it in 1960s with the releax map lapora verita.'],
  mobileTitle: 'Multi-Post Stories',
  mobileText: ['Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry´s standard dummy text ever since the 1500s,',
   'when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into',
   'electronic typesetting, remaining essent'],
  tools: ['html', 'bootstrap', 'Ruby on Rails'],
  closeImage: 'img/x-mobile.png',
  liveBtn: 'See live',
  sourceBtn: 'See source',
  live: 'https://eamador1.github.io/portfolio/',
  source: 'https://github.com/eamador1/portfolio/blob/main/index.html',
 },
]
